### ISSUE TITLE
eth0 no longer works after apt upgrade

### ISSUE THREAD

**Issue by sigma67** [AbelCS/ubuntu-server-bionic-rpi-3-b-plus#1]
I tried out your image and on first boot everything worked fine. After running apt upgrade, the "sudo netplan apply" no longer works however to fix the startup issues with eth0. Any suggestions on how to fix this?

**Comment by AbelCS** [comment]
I will take a look and try solve it, meanwhile maybe you can try https://github.com/AbelCS/ubuntu-server-bionic-rpi-3-b-plus/issues/2#issuecomment-437578618

**Comment by AbelCS** [comment]
I'm closing this issue and we can continue in #2
